### PR TITLE
Caitlindaitch solution

### PR DESCRIPTION
**Pull request by caitlindaitch**
Comfort Level: 4
Completeness: 5

### CODE REVIEW

**Comment by RobertAKARobin** [comment]
Hm. Can you be more specific about what's happening/what isn't happening?

**Comment by caitlindaitch** [comment]
Thank you so much for responding! Basically the event listener that I have that leads you into the assessStatus function only seems to work once. If I click again, the portion of the if statement for when gameInProgress === true should run (I think) but it doesn't do anything. I've done a console.log and it's just not registering a second click. Is that normal?

**Comment by RobertAKARobin** [comment]
Your event listener's working just fine! The problem's in these lines:

``` js
      if (self.gameInProgress) {
        self.counter.val(self.currentValue);
        self.gameInProgress = false;
      } else {
        self.playGame();
      }
```

Under the first condition, you're setting `self.counter`'s value to `self.currentValue`... but they're already the same thing!

Also, `self.playGame()` doesn't stop the old interval: it just creates a new one. You'll notice if you click on the timer a bunch of times it starts counting down faster and faster. That's a result of all the intervals playing on top of each other. You'll need to `clearInterval` to prevent that from happening.

**Comment by caitlindaitch** [comment]
Awesome--thank you so much!!

**Pull request closed without merging**
